name: Validate NiceEditor

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  validate:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set PowerShell execution policy
        shell: pwsh
        run: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
      - name: Run validation
        shell: pwsh
        run: |
          pwsh -NoProfile -Command ".\Validate-NiceEditor.ps1 -ProjectDir ${{ github.workspace }}"
